### ISSUE TITLE
`npm run build` creates `-p` directory

### ISSUE THREAD

**Issue by JoshuaSCochrane** [efritz/arrows#12]
For some reason when I run `npm run build`, it works the first time, but erroneously creates a directory `-p` in addition to `dist` - I assume from the gulp-task `build-parser` command `mkdir -p dist`, which _should_ be fine. Deleting both directories (`rm -rf ./-p/ dist/`) allows me to cleanly rebuild (may be another issue/request to create a rebuild or clean, but it's easy enough to rm), but still creates `./-p/`.

Running `mkdir -p dist` by itself works fine (even `mkdir -p dist/dist/dist` for good measure), so I'm not sure what's going on when it's run via gulp...

Win7x64 with git for Windows v2.10.0.windows.1, GNU bash, version 4.3.46(2)-release.

**Comment by efritz** [comment]
Can you give me the output of man mkdir? -p should create the paths "with parent directories" and not error if it already exists.

**Comment by JoshuaSCochrane** [comment]
Like I said, running `mkdir -p dist` by itself in msysgit works fine (even `mkdir -p dist/dist/dist` for good measure - creates nested `dist` dirs), which is why I don't think it's a problem with msysgit...

Looking at the [gul-shell](https://www.npmjs.com/package/gulp-shell) docs, though, it looks like the '[shell](https://www.npmjs.com/package/gulp-shell#optionsshell)' used for `task.shell` defaults to... `cmd.exe` on Windows. Sure enough, if I try `mkdir -p dist` in raw cmd, I get a `-p` directory... There are options here for choosing the shell, but I can't seem to make anything behave properly in that regard - it seems to be ignoring that option, but I can set 'verbose', 'quiet', etc. just fine...

[This SO post](https://stackoverflow.com/q/29718415/880767) mentions the same problem with win/cmd (though their command actually wasn't even defined, which helped in a way), and the answer simply says "As for the Win problem: Git bash is still no Unix shell. You should try Cygwin or consorts to make that work." (sigh) fair enough. I think the `-p` could potentially be avoided with `options.ignoreErrors`, but then we'd have to split up the commands and it may not be exactly the same. Ugh. It's not worth much, but I'll think about it and re-open if I figure something out.
