### ISSUE TITLE
Missing colon in Boolean 'lift' helper

### ISSUE THREAD

**Issue by JoshuaSCochrane** [efritz/arrows#16]
https://github.com/efritz/arrows/blob/13be431cebd7681717b9390a3b4609ed54b4feb2/src/arrows.js#L92

Should be ` /* @arrow :: _ ~> Bool */ `. I created a String lift based on this and didn't realize it wasn't getting parsed correctly. `Number.lift` is fine & works fine.

Would you prefer I create pull requests for these types of bugs/typos? I figure it can wait until you fix something else, so didn't want to go through the formality of a PR... but an issue is maybe nearly as formal as a PR - perhaps email would be preferred for non-critical fixes?

**Comment by efritz** [comment]
PRs are always welcome. If you're free could you do it and I could merge right now?

**Comment by JoshuaSCochrane** [comment]
I'm on it; five mins...

**Comment by JoshuaSCochrane** [comment]
Shall I add a helper for String while I'm at it?

**Comment by efritz** [comment]
Sure!
